### ISSUE TITLE
50$ - Github Actions - Github Action to aggregate all weekly additions from a README

### ISSUE THREAD

**Issue by ninjamuffin99** [FunkinCrew/funkinBounties#2]
**Introductory Information:**

_[Github Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) is a continuous integration and continuous delivery (CI/CD) platform that allows you to automate your build, test, and deployment pipeline. You can create workflows that build and test every pull request to your repository, or deploy merged pull requests to production._

For our use case, we are simply going to use it for some automated scripting type beat!

We have a few new repos that we've been slowly on and off cookin' on. 
- [Funkin.me Blog ](https://github.com/FunkinCrew/funkBlog)- a static site generated weekly dev blog by us, The Funkin' Crew
- [Funkin-resources](https://github.com/FunkinCrew/funkin-resources) - a community contributed/curated list of RESOURCES and COOL STUFF related to Friday Night Funkin', it's just a readme.md file right now

**The Project:**

 A Github Action that runs once a week (and/or on TRIGGER) that gets all the ADDITIONS or whatever from the pull requests over the past week, and aggregates them into a small markdown list, with links to the PRs and whatnot

What counts as an "ADDITION"? Something that was NOT in the repo before! In our case, we are going to use this for funkin-resources, and then put the output file into the funkin-blog! If someone makes a pull request and adds a new link, that should be included!

Just a clarification, all you need to do is make the part of the Github Action that gets all the additions! I can handle spitting it out to the Funkin blog!

**Prerequisites:**

Github Actions knowhow, which pretty much entails decent cute little command line knowhow. Github Actions has free minutes for public repos, so shouldn't be a problem for you to test out teehee

May or may not also need knowhow on git commits and diffs and shit like dat!!!

**How Much Can ninjamuffin Help?**
- I am decent with Github Actions and have a few handy things up my sleeve here and there. I can definitely do this small bounty myself... but I am very busy this week... bwahahaha! 

**Budget/Timeline**:

My dipshit estimate is that this can probably be done in a short afternoon or so. I just am too lazy lol! I really mean it when I say it seems straightforward! Currently have 50$ USD allocated, but can prob toss you bit more if it takes longer than an hour or two.

No rush or timeline on this though, it's a pretty quality of life feature!

**Comment by steviegt6** [comment]
Don't know if I plan on doing this myself (at school for the next several hours), but I'd like to clarify: are you looking for an action that just aggregates a list of merged PRs? Or are you looking for diffs as well? Or are you looking to aggregate commits? Or something else?

Assuming you just want a list of PR titles with links to them, this could be done rather easily if you were to squash and merged instead of just merging normally. Squashing a PR will merge the PR as a single commit with a cohesive title which is easily parseable by an automated tool, and the PR number is referenced for easy linking. Once that becomes common practice, it would be quite simple to collect a list within a certain date range.

**Comment by steviegt6** [comment]
And for the record, parsing regular PR commits is easy as well, but leaves more clutter to sift through.

**Comment by ninjamuffin99** [comment]
hmmm basically it takes like... the diffs i suppose is the right way to put it? essentially think of it like it's creating a homemade LOG of commits that add to the readme.

**Comment by steviegt6** [comment]
Could you write out a sample maybe? Diffs specifically refer to the patches that git creates, which can be seen rather easily without needing to do any of this at all.

**Comment by ninjamuffin99** [comment]
issue 62 and 64 in here: 
https://github.com/FunkinCrew/funkin-resources/pulls?q=is%3Apr+is%3Aclosed 

if you look at files changed, it's just about a single line in the readme!

Although as of right now before you commented, i will say it was claimed by someone who messaged me on Discord earlier! So to give em fair shot I'll call this one claimed!

**Comment by steviegt6** [comment]
Gotcha. I'll just leave what I was typing here and be on my way: if you're looking just for a way to view the changes made between commits, you can do so in GitHub using the link `https://github.com/user/repo/compare/commit1...commit2`. You can use release tags and even dates instead of commits, as well as across forks. Example: https://github.com/FunkinCrew/funkin-resources/compare/39f898b...6549b0e.

Further reading (details two-dot vs. three-dot diff comparisons, formatting, and more): https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits

**Comment by Aurel300** [comment]
@ninjamuffin99 this can be closed!

**Comment by ninjamuffin99** [comment]
closed with https://github.com/FunkinCrew/funkin-resources/pull/69
